version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: freelancerconsumer
    ports:
      - 5000:5000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - freelancer
      - db_network

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - freelancerconsumer_data:/var/lib/postgresql/data
    networks:
      - db_network

networks: 
  freelancer: 
    external: true
  db_network:
    external: false

volumes:
  freelancerconsumer_data: